runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app
runtime_config:
    operating_system: "ubuntu18"
    runtime_version: "3.10"
resources:
  cpu: 4
  memory_gb: 16
  disk_size_gb: 20
handlers:
- url: /health
  script: auto

- url: /suggest
  script: auto

- url: /predict_genre
  script: auto

